# Generated by Django 3.2 on 2022-08-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_filmwork_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genrefilmwork',
            old_name='filmwork',
            new_name='film_work',
        ),
    ]
